export default {
    CART_AMOUNT_INCREMENT: 'CART_AMOUNT_INCREMENT',
    CART_AMOUNT_DECREMENT: 'CART_AMOUNT_DECREMENT',
    // 开始请求数据
    START_FETCH_DATA: 'START_FETCH_DATA',
    // 数据请求成功
    FETCH_DATA_SUCCESS: 'FETCH_DATA_SUCCESS',
    // 数据请求失败
    FETCH_DATA_FAIL: 'FETCH_DATA_FAIL'
}